# Generated by Django 2.2.7 on 2019-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='newsfeed-default.jpg', upload_to='newsfeed_pics'),
        ),
    ]
